---
  # Kubernetes installation finalize
  - name: Kubernetes installation finalize
    debug:
      msg:
        - "Finished installing Kubernetes."
        - "Please validate that all containers are 'Running' using:"
        - "kubectl get pods --all-namespaces"
        - "it may take a few minutes before all containers are running."
        - ""
        - "Once all containers are running open the Kubernetes Dashboard:"
        - "https://{{item}}:{{dashboard_service_port}}"
    with_items:
      -  "{{groups['masternode']}}"


